# .gitlab-ci.yml
#

stages:
  - check
  - test
  - build
  - publish

variables:
  GIT_STRATEGY: fetch
  GIT_DEPTH: "100"
  CARGO_INCREMENTAL: 0
  CI_IMAGE: "paritytech/ci-unified:latest"

default:
  cache: {}
  interruptible: true
  retry:
    max: 2
    when:
      - runner_system_failure
      - unknown_failure
      - api_failure

.kubernetes-env:
  image: $CI_IMAGE
  tags:
    - kubernetes-parity-build

tests:
  stage: test
  extends: .kubernetes-env
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^[0-9]+$/ # PRs
    - if: $CI_COMMIT_REF_NAME == "master"
  script:
    - echo "run always (but not with tags)"

publish-dry-run:
  stage: publish
  extends: .kubernetes-env
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^[0-9]+$/ # PRs
  script:
    - echo "run only in PR"

publish-crate:
  stage: publish
  extends: .kubernetes-env
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^v[0-9]+\.[0-9]+.*$/ # i.e. v1.0, v2.1rc1
  script:
    - echo "run only when tag/release is set"
